# Generated by Django 4.2.23 on 2025-07-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
